# Generated by Django 6.0.4 on 2026-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO'), ('delivery', 'Delivery Person'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO'), ('delivery', 'Delivery Person'), ('admin', 'Admin')], default='donor', max_length=20),
        ),
    ]
