# Generated by Django 6.0.4 on 2026-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_is_available_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='ai_quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
