# Generated by Django 6.0.4 on 2026-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fooddonation_ai_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='urgency_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=20),
        ),
    ]
