# Generated by Django 6.0.4 on 2026-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fooddonation_urgency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='pickup_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='pickup_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
