# Generated by Django 6.0.4 on 2026-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fooddonation_pickup_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
