# Generated by Django 6.0.4 on 2026-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fooddonation_latitude_fooddonation_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='food_condition',
            field=models.CharField(default='Fresh', max_length=50),
        ),
    ]
