# Generated by Django 6.0.4 on 2026-05-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fooddonation_food_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='picked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
